1 2.155   File "<frozen runpy>", line 88, in _run_code
2024-Dec-27 17:06:07.604355
#11 2.155   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/ensurepip/__main__.py", line 5, in <module>
2024-Dec-27 17:06:07.604355
#11 2.155     sys.exit(ensurepip._main())
2024-Dec-27 17:06:07.604355
#11 2.158              ^^^^^^^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
#11 2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/ensurepip/__init__.py", line 286, in _main
2024-Dec-27 17:06:07.604355
#11 2.158     return _bootstrap(
2024-Dec-27 17:06:07.604355
#11 2.158            ^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
#11 2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/ensurepip/__init__.py", line 202, in _bootstrap
2024-Dec-27 17:06:07.604355
#11 2.158     return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
2024-Dec-27 17:06:07.604355
#11 2.158            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
#11 2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/ensurepip/__init__.py", line 103, in _run_pip
2024-Dec-27 17:06:07.604355
#11 2.158     return subprocess.run(cmd, check=True).returncode
2024-Dec-27 17:06:07.604355
#11 2.158            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
#11 2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/subprocess.py", line 571, in run
2024-Dec-27 17:06:07.604355
#11 2.158     raise CalledProcessError(retcode, process.args,
2024-Dec-27 17:06:07.604355
#11 2.158 subprocess.CalledProcessError: Command '['/root/.nix-profile/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpg0hqnutj/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmpg0hqnutj/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpg0hqnutj\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
2024-Dec-27 17:06:07.604355
#11 ERROR: process "/bin/bash -ol pipefail -c python3 -m ensurepip" did not complete successfully: exit code: 1
2024-Dec-27 17:06:07.604355
------
2024-Dec-27 17:06:07.604355
 > [ 7/15] RUN  python3 -m ensurepip:
2024-Dec-27 17:06:07.604355
2.158            ^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/ensurepip/__init__.py", line 202, in _bootstrap
2024-Dec-27 17:06:07.604355
2.158     return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
2024-Dec-27 17:06:07.604355
2.158            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/ensurepip/__init__.py", line 103, in _run_pip
2024-Dec-27 17:06:07.604355
2.158     return subprocess.run(cmd, check=True).returncode
2024-Dec-27 17:06:07.604355
2.158            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-Dec-27 17:06:07.604355
2.158   File "/nix/store/plr4xql151m3gwycfik7asjz8xifbbv7-python3-3.11.9/lib/python3.11/subprocess.py", line 571, in run
2024-Dec-27 17:06:07.604355
2.158     raise CalledProcessError(retcode, process.args,
2024-Dec-27 17:06:07.604355
2.158 subprocess.CalledProcessError: Command '['/root/.nix-profile/bin/python3', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmpg0hqnutj/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmpg0hqnutj/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmpg0hqnutj\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
2024-Dec-27 17:06:07.604355
------
2024-Dec-27 17:06:07.604355
2024-Dec-27 17:06:07.604355
 1 warning found (use docker --debug to expand):
2024-Dec-27 17:06:07.604355
 - UndefinedVar: Usage of undefined variable '$NIXPACKS_PATH' (line 18)
2024-Dec-27 17:06:07.604355
Dockerfile:20
2024-Dec-27 17:06:07.604355
--------------------
2024-Dec-27 17:06:07.604355
  18 |     ENV NIXPACKS_PATH=/opt/venv/bin:$NIXPACKS_PATH
2024-Dec-27 17:06:07.604355
  19 |     COPY . /app/.
2024-Dec-27 17:06:07.604355
  20 | >>> RUN  python3 -m ensurepip
2024-Dec-27 17:06:07.604355
  21 |     RUN  python3 -m pip install --upgrade pip
2024-Dec-27 17:06:07.604355
  22 |     RUN  python3 -m pip install -r requirements.txt
2024-Dec-27 17:06:07.604355
--------------------
2024-Dec-27 17:06:07.604355
ERROR: failed to solve: process "/bin/bash -ol pipefail -c python3 -m ensurepip" did not complete successfully: exit code: 1
2024-Dec-27 17:06:07.612211
Deployment failed. Removing the new version of your application.